package com.dota.tracker.opendota.model

data class Actions(
    val `1`: Int,
    val `10`: Int,
    val `11`: Int,
    val `12`: Int,
    val `14`: Int,
    val `15`: Int,
    val `16`: Int,
    val `17`: Int,
    val `18`: Int,
    val `19`: Int,
    val `2`: Int,
    val `20`: Int,
    val `21`: Int,
    val `24`: Int,
    val `3`: Int,
    val `31`: Int,
    val `32`: Int,
    val `33`: Int,
    val `4`: Int,
    val `40`: Int,
    val `42`: Int,
    val `5`: Int,
    val `6`: Int,
    val `7`: Int,
    val `8`: Int,
    val `9`: Int
)